# fly.toml app configuration file generated for db-issy-tommaso-james-tess-woo on 2023-09-26T14:57:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "db-issy-tommaso-james-tess-woo"
primary_region = "lhr"

[build]

[mounts]
  source = "data"
  destination = "/data"

# [env]
#   DB_FILE = "restaurantapp.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
